# Workflow for deploying the COS 420 Team D project as a website on GitHub Pages

name: Deploy COS 420 Team D as website

on:
    push:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci
              working-directory: "COS 420 Team D"

            - name: Build the project
              run: npm run build
              working-directory: "COS 420 Team D"

            - name: Setup Pages
              uses: actions/configure-pages@v3

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: "COS 420 Team D/dist"

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v1
