name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    # Cache npm dependencies
    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          "COS 420 Team D/src/node_modules"
          "~/.npm"
        key: ${{ runner.os }}-node-${{ hashFiles('COS 420 Team D/src/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install dependencies
    - run: npm ci

    # Run build and tests
    - run: CI= npm run build --if-present
    - run: npm test
